version: '3.1'
services:
  manp:
    image: cobers/manp
    container_name: manp
    restart: unless-stopped
    volumes:
      - ./web:/www
    ports:
      - 8686:80
  mysql:
    image: mariadb:10.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - ./data:/var/lib/mysql